; ADDING TWO NUMBER WITH INPUTTED VALUE

.MODEL SMALL
.STACK 100H
.DATA
.CODE
    MAIN PROC
        
    MOV AH, 1     ; SETTING UP INPUT MOOD
    INT 21H       ; TAKING INPUT FOR NUMBER 1
    MOV BH, AL    ; MOVING DATA TO NUMBER 1 FROM INPUT REG AL
    INT 21H       ; TAKING INPUT FOR NUMBER 2
    MOV BL, AL    ; MOVING DATA TO NUMBER 2 FROM INPUT REG AL
    
    ADD BH, BL    ; DOING NUMBER 1 = NUMBER 1 + NUMBER 2
    SUB BH, 30H   ; CONVERTING TO CHAR
    
    MOV AH, 2     ; SETTING UP OUTPUT MOOD
    
    MOV DL, 0DH   ; NEXT 4 LINE WILL PRINT A NEWLINE
    INT 21H
    MOV DL, 0AH
    INT 21H
    
    MOV DL, BH    ; MOVING SUMMATION TO OUTPUT REG DL
    INT 21H       ; PRINTING OUTPUT 
        
    MAIN ENDP
END MAIN
