; ADDING THREE NUMBER

.MODEL SMALL
.STACK 100H
.DATA
.CODE
    MAIN PROC
        MOV BH, 3     ; DECLARING NUMBER 1
        MOV BL, 4     ; DECLARING NUMBER 2
        MOV CH, 2     ; DECLARING NUMBER 3
        ADD CH, BL    ; DOING NUMBER 1 = NUMBER 1 + NUMBER 2
        ADD CH, BH    ; DOING NUMBER 1 = NUMBER 1 + NUMBER 3
        ADD CH, 30H   ; CONVERTING TO CHAR
        MOV DL, CH    ; MOVING DATA TO OUTPUT REG DL
        MOV AH, 2     ; SETTING UP OUTPUT MOOD
        INT 21H       ; OUTPUT/PRINT COMMAND
        
    MAIN ENDP
END MAIN
